# Generated by Django 5.1.6 on 2025-02-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_reminder_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(default='teste', max_length=255),
            preserve_default=False,
        ),
    ]
